package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Filmas;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface FilmasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.filmas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    int deleteByPrimaryKey(Integer filmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.filmas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    int insert(Filmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.filmas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    Filmas selectByPrimaryKey(Integer filmoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.filmas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    List<Filmas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.filmas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    int updateByPrimaryKey(Filmas record);
}