package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Klientas;
import org.mybatis.cdi.Mapper;


import java.util.List;

@Mapper
public interface KlientasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.klientas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    int deleteByPrimaryKey(Integer klientoNr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.klientas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    int insert(Klientas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.klientas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    Klientas selectByPrimaryKey(Integer klientoNr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.klientas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    List<Klientas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.klientas
     *
     * @mbg.generated Thu Mar 23 09:42:23 EET 2017
     */
    int updateByPrimaryKey(Klientas record);
}